AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'

Documentation:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable

Lint/HandleExceptions:
  Enabled: false

Metrics/LineLength:
  Max: 140

Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/SingleLineBlockParams:
  Methods: []

Style/SpaceInsideBrackets:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrivialAccessors:
  AllowPredicates: true

Style/WordArray:
  MinSize: 5
